### ISSUE TITLE
laravel filament php 

### ISSUE THREAD

**Issue by Q8hma** [still-code/ar-php-laravel#40]
Hello

I have one question, does it support filament?

thanks

**Comment by atmonshi** [comment]
its a php package, and you can use it anywhere in laravel, filament or other

what is your use cases?

**Comment by atmonshi** [comment]
ya but like where?
in global search? in table search? in select component?

anyway you can do somthing like this:

```php
TextColumn::make('title')
    ->searchable(query: function (Builder $query, string $search): Builder {
        return $query->searchAr('title',$search);
    })
```
