### ISSUE TITLE
Some characters give error

### ISSUE THREAD

**Issue by m3aarfRepo** [still-code/ar-php-laravel#41]
**Describe the bug**
i am using your package to render Arabic text inside images but i found that there is
a word cause error

**To Reproduce**
Try execute  ArPhpLaravel::utf8Glyphs($text)
with this word "للاستكشاف"

**Code Example**
$result =  ArPhpLaravel::utf8Glyphs($result);

**Versions:**
 - PHP: 8.2
 - Laravel: 10
 - Packeage: "still-code/ar-php-laravel": "^2.0"

Error Undefined array key -1 
I found that this part للا is the problem

**Comment by atmonshi** [comment]
my package is just a warper around the main package:
https://github.com/khaled-alshamaa/ar-php

try this:
```php
$arabic = new \ArPHP\I18N\Arabic();
$result = $arabic->utf8Glyphs('للاستكشاف');
```

if still an issue, you can open an issue there.
